module SportsOddsAPI
  module Models
    type account_get_usage_params =
      {  } & SportsOddsAPI::Internal::Type::request_parameters

    class AccountGetUsageParams < SportsOddsAPI::Internal::Type::BaseModel
      extend SportsOddsAPI::Internal::Type::RequestParameters::Converter
      include SportsOddsAPI::Internal::Type::RequestParameters

      def initialize: (?request_options: SportsOddsAPI::request_opts) -> void

      def to_hash: -> { request_options: SportsOddsAPI::RequestOptions }
    end
  end
end
