module SportsOddsAPI
  module Resources
    class Teams
      def get: (
        ?cursor: String,
        ?league_id: String,
        ?limit: Float,
        ?sport_id: String,
        ?team_id: String,
        ?request_options: SportsOddsAPI::request_opts
      ) -> SportsOddsAPI::Internal::NextCursorPage[SportsOddsAPI::Team]

      def initialize: (client: SportsOddsAPI::Client) -> void
    end
  end
end
